//left is topojson right is UN data
countryMapper = {
  "Angola": "Angola",
  "Albania": "Albania",
  "Argentina": "Argentina",
  "Armenia": "Armenia",
  "Australia": "Australia",
  "Austria": "Austria",
  "Azerbaijan": "Azerbaijan",
  "Burundi": "Burundi",
  "Belgium": "Belgium",
  "Benin": "Benin",
  "Burkina Faso": "Burkina Faso",
  "Bangladesh": "Bangladesh",
  "Bulgaria": "Bulgaria",
  "Bosnia and Herzegovina": "Bosnia and Herzegovina",
  "Belarus": "Belarus",
  "Brazil": "Brazil",
  "Bhutan": "Bhutan",
  "Botswana": "Botswana",
  "Central African Republic": "Central African Republic",
  "Canada": "Canada",
  "Switzerland": "Switzerland",
  "Chile": "Chile",
  "China": "China",
  "Cameroon": "Cameroon",
  "Democratic Republic of the Congo": "Democratic Republic of the Congo",
  "Colombia": "Colombia",
  "Costa Rica": "Costa Rica",
  "Cyprus": "Cyprus",
  "Germany": "Germany",
  "Djibouti": "Djibouti",
  "Denmark": "Denmark",
  "Dominican Republic": "Dominican Republic",
  "Algeria": "Algeria",
  "Ecuador": "Ecuador",
  "Egypt": "Egypt",
  "Spain": "Spain",
  "Estonia": "Estonia",
  "Ethiopia": "Ethiopia",
  "Finland": "Finland",
  "Fiji": "Fiji",
  "France": "France",
  "Gabon": "Gabon",
  "Georgia": "Georgia",
  "Ghana": "Ghana",
  "Guinea": "Guinea",
  "Gambia": "Gambia",
  "Greece": "Greece",
  "Guatemala": "Guatemala",
  "Honduras": "Honduras",
  "Croatia": "Croatia",
  "Haiti": "Haiti",
  "Hungary": "Hungary",
  "Indonesia": "Indonesia",
  "India": "India",
  "Ireland": "Ireland",
  "Iraq": "Iraq",
  "Iceland": "Iceland",
  "Israel": "Israel",
  "Italy": "Italy",
  "Jamaica": "Jamaica",
  "Jordan": "Jordan",
  "Japan": "Japan",
  "Kazakhstan": "Kazakhstan",
  "Kenya": "Kenya",
  "Kyrgyzstan": "Kyrgyzstan",
  "Lebanon": "Lebanon",
  "Liberia": "Liberia",
  "Sri Lanka": "Sri Lanka",
  "Lesotho": "Lesotho",
  "Lithuania": "Lithuania",
  "Luxembourg": "Luxembourg",
  "Latvia": "Latvia",
  "Morocco": "Morocco",
  "Madagascar": "Madagascar",
  "Mexico": "Mexico",
  "Mali": "Mali",
  "Myanmar": "Myanmar",
  "Montenegro": "Montenegro",
  "Mongolia": "Mongolia",
  "Mozambique": "Mozambique",
  "Mauritania": "Mauritania",
  "Malawi": "Malawi",
  "Malaysia": "Malaysia",
  "Namibia": "Namibia",
  "Niger": "Niger",
  "Nigeria": "Nigeria",
  "Nicaragua": "Nicaragua",
  "Netherlands": "Netherlands",
  "Norway": "Norway",
  "Nepal": "Nepal",
  "Pakistan": "Pakistan",
  "Panama": "Panama",
  "Peru": "Peru",
  "Philippines": "Philippines",
  "Papua New Guinea": "Papua New Guinea",
  "Poland": "Poland",
  "Portugal": "Portugal",
  "Paraguay": "Paraguay",
  "Romania": "Romania",
  "Rwanda": "Rwanda",
  "Sudan": "Sudan",
  "South Sudan": "South Sudan",
  "Senegal": "Senegal",
  "Solomon Islands": "Solomon Islands",
  "Sierra Leone": "Sierra Leone",
  "El Salvador": "El Salvador",
  "Slovakia": "Slovakia",
  "Slovenia": "Slovenia",
  "Sweden": "Sweden",
  "Chad": "Chad",
  "Togo": "Togo",
  "Thailand": "Thailand",
  "Tajikistan": "Tajikistan",
  "Tunisia": "Tunisia",
  "Turkey": "Turkey",
  "United Republic of Tanzania": "United Republic of Tanzania",
  "Uganda": "Uganda",
  "Ukraine": "Ukraine",
  "Uruguay": "Uruguay",
  "Uzbekistan": "Uzbekistan",
  "Vanuatu": "Vanuatu",
  "Yemen": "Yemen",
  "South Africa": "South Africa",
  "Zambia": "Zambia",
  "Zimbabwe": "Zimbabwe",
  "Bolivia": "Bolivia (Plurinational State of)",
  "Ivory Coast": "Côte d'Ivoire",
  "Northern Cyprus": "Cyprus",
  "Czech Republic": "Czechia",
  "England": "United Kingdom of Great Britain and Northern Ireland",
  "Guinea Bissau": "Guinea-Bissau",
  "Iran": "Iran (Islamic Republic of)",
  "South Korea": "Republic of Korea",
  "Laos": "Lao People's Democratic Republic",
  "Moldova": "Republic of Moldova",
  "Macedonia": "North Macedonia",
  "New Zealand": "Australia and New Zealand",
  "Russia": "Russian Federation",
  "Republic of Serbia": "Serbia",
  "Swaziland": "Eswatini",
  "Syria": "Syrian Arab Republic",
  "East Timor": "Timor-Leste",
  "USA": "United States of America",
  "Venezuela": "Venezuela (Bolivarian Republic of)",
  "Vietnam": "Viet Nam"
}